name: polymer_example
version: 0.0.1
description: A starter template for a polymer.dart web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  core_elements: '>=0.6.0+4 <0.7.0'
  google_maps: '>=2.0.0 <3.0.0'
  logging: any
  paper_elements: '>=0.6.1 <0.7.0'
  polymer: '>=0.15.4 <0.16.0'
  route_hierarchical: '>=0.5.0 <0.7.0'
transformers:
- polymer:
    entry_points: web/index.html
